export const countries = [
  { country: "Israel", population: 7208000, region: "Asia Occidental", flag: "🇮🇱" },
  { country: "Estados Unidos", population: 6300000, region: "Norteamerica", flag: "🇺🇸" },
  { country: "Francia", population: 438500, region: "Europa Occidental", flag: "🇫🇷" },
  { country: "Canada", population: 400000, region: "Norteamerica", flag: "🇨🇦" },
  { country: "Reino Unido", population: 312000, region: "Europa Occidental", flag: "🇬🇧" },
  { country: "Argentina", population: 171000, region: "America Latina", flag: "🇦🇷" },
  { country: "Rusia", population: 132000, region: "Europa Oriental", flag: "🇷🇺" },
  { country: "Alemania", population: 118000, region: "Europa Occidental", flag: "🇩🇪" },
  { country: "Australia", population: 117200, region: "Oceania", flag: "🇦🇺" },
  { country: "Brasil", population: 92000, region: "America Latina", flag: "🇧🇷" },
  { country: "Sudafrica", population: 49500, region: "Africa", flag: "🇿🇦" },
  { country: "Hungria", population: 47000, region: "Europa Central", flag: "🇭🇺" },
  { country: "Ucrania", population: 43000, region: "Europa Oriental", flag: "🇺🇦" },
  { country: "Mexico", population: 40000, region: "America Latina", flag: "🇲🇽" },
  { country: "Paises Bajos", population: 29700, region: "Europa Occidental", flag: "🇳🇱" },
  { country: "Belgica", population: 29000, region: "Europa Occidental", flag: "🇧🇪" },
  { country: "Italia", population: 27000, region: "Europa Meridional", flag: "🇮🇹" },
  { country: "Suiza", population: 20000, region: "Europa Central", flag: "🇨🇭" },
  { country: "Chile", population: 18300, region: "America Latina", flag: "🇨🇱" },
  { country: "Uruguay", population: 16300, region: "America Latina", flag: "🇺🇾" },
  { country: "Suecia", population: 15000, region: "Europa Nordica", flag: "🇸🇪" },
  { country: "Turquia", population: 14500, region: "Asia/Europa", flag: "🇹🇷" },
  { country: "Espana", population: 13000, region: "Europa Meridional", flag: "🇪🇸" },
  { country: "Belarus", population: 12900, region: "Europa Oriental", flag: "🇧🇾" },
  { country: "Austria", population: 10300, region: "Europa Central", flag: "🇦🇹" },
  { country: "Panama", population: 10000, region: "America Central", flag: "🇵🇦" },
  { country: "Rumania", population: 9300, region: "Europa Oriental", flag: "🇷🇴" },
  { country: "Azerbaiyan", population: 8100, region: "Caucaso", flag: "🇦🇿" },
  { country: "Grecia", population: 6700, region: "Europa Meridional", flag: "🇬🇷" },
  { country: "Nueva Zelanda", population: 7500, region: "Oceania", flag: "🇳🇿" },
  { country: "Dinamarca", population: 6400, region: "Europa Nordica", flag: "🇩🇰" },
  { country: "Letonia", population: 6200, region: "Baltico", flag: "🇱🇻" },
  { country: "Polonia", population: 4500, region: "Europa Central", flag: "🇵🇱" },
  { country: "Serbia", population: 4000, region: "Balcanes", flag: "🇷🇸" },
  { country: "Portugal", population: 3300, region: "Europa Meridional", flag: "🇵🇹" },
  { country: "China", population: 3000, region: "Asia Oriental", flag: "🇨🇳" },
  { country: "Uzbekistan", population: 2900, region: "Asia Central", flag: "🇺🇿" },
  { country: "Irlanda", population: 2700, region: "Europa Occidental", flag: "🇮🇪" },
  { country: "Eslovaquia", population: 2600, region: "Europa Central", flag: "🇸🇰" },
  { country: "Kazajistan", population: 2500, region: "Asia Central", flag: "🇰🇿" },
  { country: "Costa Rica", population: 2500, region: "America Central", flag: "🇨🇷" },
  { country: "Lituania", population: 2400, region: "Baltico", flag: "🇱🇹" },
  { country: "Marruecos", population: 2100, region: "Africa del Norte", flag: "🇲🇦" },
  { country: "Croacia", population: 1700, region: "Balcanes", flag: "🇭🇷" }
];
